apiVersion: v2
name: helloapp
description: Helm chart for the Google "hello-app" web server, with health checks, autoscaling, optional Ingress and hardened security defaults
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - hello-app
  - web
  - kubernetes
maintainers:
  - name: demanou
    url: https://github.com/demanou
sources:
  - https://github.com/demanou/helmchart-template-deployment
